# Generated by Django 5.2.13 on 2026-04-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('instant', 'instant'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('hour', models.PositiveSmallIntegerField(default=9)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=42)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('employer_address', models.CharField(blank=True, default='', max_length=42)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('paused', 'paused'), ('completed', 'completed')], default='draft', max_length=16)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chains.chain')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofhe.scheduleconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('deadline_u64', models.BigIntegerField()),
                ('employee_count_u32', models.PositiveIntegerField()),
                ('required_total_atomic', models.BigIntegerField(default=0)),
                ('onchain_payroll_id', models.BigIntegerField(blank=True, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=42)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('create_broadcasted', 'create_broadcasted'), ('created', 'created'), ('alloc_uploading', 'alloc_uploading'), ('alloc_uploaded', 'alloc_uploaded'), ('alloc_finalizing', 'alloc_finalizing'), ('alloc_finalized', 'alloc_finalized'), ('funding', 'funding'), ('funded', 'funded'), ('activating', 'activating'), ('active', 'active'), ('closed', 'closed'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='scheduled', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('create_tx_hash', models.CharField(blank=True, max_length=80)),
                ('fund_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('activate_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('funded_once_handle', models.CharField(blank=True, max_length=66)),
                ('funded_plaintext', models.BooleanField(blank=True, null=True)),
                ('funded_sig', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chains.chain')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='cofhe.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RunAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_address', models.CharField(max_length=42)),
                ('amount_atomic', models.BigIntegerField()),
                ('amount_ciphertext_hex', models.TextField(blank=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_tx_hash', models.CharField(blank=True, max_length=80)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cofhe.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='SwapRouterWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42)),
                ('request_tx_hash', models.CharField(blank=True, max_length=80)),
                ('finalize_tx_hash', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=66)),
                ('pending_amount_handle', models.CharField(blank=True, max_length=66)),
                ('pending_ok_handle', models.CharField(blank=True, max_length=66)),
                ('pending_request_id', models.CharField(blank=True, max_length=66)),
                ('amount_plaintext', models.BigIntegerField(blank=True, null=True)),
                ('amount_sig', models.TextField(blank=True)),
                ('ok_plaintext', models.BooleanField(blank=True, null=True)),
                ('ok_sig', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('request_broadcasted', 'request_broadcasted'), ('pending_ready', 'pending_ready'), ('finalize_broadcasted', 'finalize_broadcasted'), ('finalized_success', 'finalized_success'), ('finalized_revert', 'finalized_revert'), ('failed', 'failed')], default='draft', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chains.chain')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_address', models.CharField(max_length=42)),
                ('amount_atomic', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cofhe.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ChainTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=80)),
                ('sender', models.CharField(blank=True, max_length=42)),
                ('to', models.CharField(blank=True, max_length=42)),
                ('nonce', models.BigIntegerField(blank=True, null=True)),
                ('intent_type', models.CharField(choices=[('PV_CREATE_PAYROLL', 'PV_CREATE_PAYROLL'), ('PV_UPLOAD_ALLOCATIONS', 'PV_UPLOAD_ALLOCATIONS'), ('PV_FINALIZE_ALLOCATIONS', 'PV_FINALIZE_ALLOCATIONS'), ('PV_FUND_PAYROLL', 'PV_FUND_PAYROLL'), ('PV_ACTIVATE_PAYROLL', 'PV_ACTIVATE_PAYROLL'), ('PV_REQUEST_CLAIM', 'PV_REQUEST_CLAIM'), ('PV_FINALIZE_CLAIM', 'PV_FINALIZE_CLAIM'), ('PV_CANCEL_CLAIM', 'PV_CANCEL_CLAIM'), ('SR_DEPOSIT', 'SR_DEPOSIT'), ('SR_REQUEST_WITHDRAW', 'SR_REQUEST_WITHDRAW'), ('SR_FINALIZE_WITHDRAW', 'SR_FINALIZE_WITHDRAW')], max_length=64)),
                ('ref_model', models.CharField(blank=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('broadcasted', 'broadcasted'), ('mined_success', 'mined_success'), ('mined_revert', 'mined_revert'), ('dropped', 'dropped'), ('replaced', 'replaced'), ('unknown', 'unknown'), ('finalized_success', 'finalized_success'), ('finalized_revert', 'finalized_revert')], default='broadcasted', max_length=32)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=80)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('replaced_by', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chains.chain')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='cofhe_chain_status_65f29a_idx'), models.Index(fields=['ref_model', 'ref_id'], name='cofhe_chain_ref_mod_515488_idx')],
                'unique_together': {('chain', 'tx_hash')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_address', models.CharField(max_length=42)),
                ('request_tx_hash', models.CharField(blank=True, max_length=80)),
                ('finalize_tx_hash', models.CharField(blank=True, max_length=80)),
                ('cancel_tx_hash', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=66)),
                ('pending_ok_handle', models.CharField(blank=True, max_length=66)),
                ('pending_request_id', models.CharField(blank=True, max_length=66)),
                ('ok_plaintext', models.BooleanField(blank=True, null=True)),
                ('ok_sig', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('request_broadcasted', 'request_broadcasted'), ('pending_ready', 'pending_ready'), ('finalize_broadcasted', 'finalize_broadcasted'), ('finalized_success', 'finalized_success'), ('finalized_revert', 'finalized_revert'), ('cancel_broadcasted', 'cancel_broadcasted'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='draft', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='cofhe.payrollrun')),
            ],
            options={
                'unique_together': {('run', 'employee_address')},
            },
        ),
        migrations.CreateModel(
            name='AllocationUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=80)),
                ('employee_count', models.PositiveIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_chunks', to='cofhe.payrollrun')),
            ],
            options={
                'unique_together': {('run', 'idempotency_key')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status', 'run_at'], name='cofhe_payro_status_1f62d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['onchain_payroll_id'], name='cofhe_payro_onchain_022c1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('template', 'run_at')},
        ),
        migrations.AlterUniqueTogether(
            name='runallocation',
            unique_together={('run', 'employee_address')},
        ),
        migrations.AddIndex(
            model_name='payrolltemplate',
            index=models.Index(fields=['status', 'next_run_at'], name='cofhe_payro_status_17ce6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolltemplate',
            index=models.Index(fields=['employer_address'], name='cofhe_payro_employe_9fb315_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprouterwithdraw',
            index=models.Index(fields=['status', 'created_at'], name='cofhe_swapr_status_59e57b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateemployee',
            unique_together={('template', 'employee_address')},
        ),
    ]
