# Generated by Django 5.2.13 on 2026-04-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofhe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprouterwithdraw',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='cofhe.claim'),
        ),
    ]
