# Generated by Django 5.2.13 on 2026-04-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
        ('cofhe', '0002_swaprouterwithdraw_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprouterwithdraw',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='cofhe.claim'),
        ),
        migrations.AddIndex(
            model_name='swaprouterwithdraw',
            index=models.Index(fields=['user_address'], name='cofhe_swapr_user_ad_1c1f87_idx'),
        ),
    ]
