# Generated by Django 5.2.13 on 2026-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofhe', '0003_alter_swaprouterwithdraw_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprouterwithdraw',
            name='cancel_tx_hash',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='swaprouterwithdraw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='swaprouterwithdraw',
            name='withdraw_key',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chaintx',
            name='intent_type',
            field=models.CharField(choices=[('PV_CREATE_PAYROLL', 'PV_CREATE_PAYROLL'), ('PV_UPLOAD_ALLOCATIONS', 'PV_UPLOAD_ALLOCATIONS'), ('PV_FINALIZE_ALLOCATIONS', 'PV_FINALIZE_ALLOCATIONS'), ('PV_FUND_PAYROLL', 'PV_FUND_PAYROLL'), ('PV_ACTIVATE_PAYROLL', 'PV_ACTIVATE_PAYROLL'), ('PV_REQUEST_CLAIM', 'PV_REQUEST_CLAIM'), ('PV_FINALIZE_CLAIM', 'PV_FINALIZE_CLAIM'), ('PV_CANCEL_CLAIM', 'PV_CANCEL_CLAIM'), ('SR_DEPOSIT', 'SR_DEPOSIT'), ('SR_REQUEST_WITHDRAW', 'SR_REQUEST_WITHDRAW'), ('SR_FINALIZE_WITHDRAW', 'SR_FINALIZE_WITHDRAW'), ('SR_CANCEL_WITHDRAW', 'SR_CANCEL_WITHDRAW')], max_length=64),
        ),
        migrations.AlterField(
            model_name='swaprouterwithdraw',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('request_broadcasted', 'request_broadcasted'), ('pending_ready', 'pending_ready'), ('finalize_broadcasted', 'finalize_broadcasted'), ('cancel_broadcasted', 'cancel_broadcasted'), ('finalized_success', 'finalized_success'), ('finalized_revert', 'finalized_revert'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='draft', max_length=32),
        ),
    ]
