# Generated by Django 5.2.13 on 2026-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofhe', '0004_swaprouterwithdraw_cancel_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runallocation',
            name='claim_completion_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runallocation',
            name='claim_invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runallocation',
            name='deadline_24h_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runallocation',
            name='deadline_3d_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runallocation',
            name='employee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='runallocation',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='templateemployee',
            name='employee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='templateemployee',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='runallocation',
            index=models.Index(fields=['employee_address'], name='cofhe_runal_employe_c44300_idx'),
        ),
        migrations.AddIndex(
            model_name='runallocation',
            index=models.Index(fields=['employee_email'], name='cofhe_runal_employe_9a3db6_idx'),
        ),
        migrations.AddIndex(
            model_name='runallocation',
            index=models.Index(fields=['claim_invitation_sent_at'], name='cofhe_runal_claim_i_2e7c57_idx'),
        ),
        migrations.AddIndex(
            model_name='runallocation',
            index=models.Index(fields=['deadline_3d_reminder_sent_at'], name='cofhe_runal_deadlin_c0367b_idx'),
        ),
        migrations.AddIndex(
            model_name='runallocation',
            index=models.Index(fields=['deadline_24h_reminder_sent_at'], name='cofhe_runal_deadlin_0aba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='templateemployee',
            index=models.Index(fields=['employee_address'], name='cofhe_templ_employe_5e9ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='templateemployee',
            index=models.Index(fields=['employee_email'], name='cofhe_templ_employe_e58366_idx'),
        ),
    ]
