# Generated by Django 5.2.13 on 2026-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rpc_url', models.CharField(max_length=256)),
                ('usdc_address', models.CharField(blank=True, max_length=42)),
                ('confidentialtoken_address', models.CharField(blank=True, max_length=42)),
                ('payrollvault_address', models.CharField(blank=True, max_length=42)),
                ('swaprouter_address', models.CharField(blank=True, max_length=42)),
                ('confirmations_required', models.PositiveIntegerField(default=3)),
                ('reorg_finality_buffer', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
