# Generated by Django 5.2.13 on 2026-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='onboarding__email_8974c8_idx',
            old_name='onboarding__email_a5ea_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='onboarding__last_se_97bf4a_idx',
            old_name='onboarding__last_se_3197_idx',
        ),
    ]
